In [2]:
import pandas as pd
import yfinance as yf
import re

c:\Users\micha\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
# Load in data and create "tickers" list
tickers = ['GBTC', 'ETHE', 'SPY', 'BND', 'GLD', 'VNQ']

# Compile all data in "equity_data" dataframe
equity_data = pd.DataFrame()
start_date = "2000-01-01"
end_date = "2025-01-01"

for ticker in tickers:
    data = yf.download(ticker, start=start_date, end=end_date, group_by='ticker')

    if isinstance(data.columns, pd.MultiIndex):
        df = data[ticker].copy()
    else:
        df = data.copy()

    df = df.reset_index()
    df['Ticker'] = ticker
    df = df[['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume']]

    equity_data = pd.concat([equity_data, df], ignore_index=True)

equity_data.columns.name = None

# Sort by Ticker and Date to ensure proper order
equity_data = equity_data.sort_values(['Ticker', 'Date']).reset_index(drop=True)

# Calculate Net Change and % Change in Close for each Ticker
equity_data['Net Change'] = equity_data.groupby('Ticker')['Close'].diff()
equity_data['% Change'] = equity_data.groupby('Ticker')['Close'].pct_change() * 100

# Export csv
equity_data.to_csv("equity_data.csv", index=False)

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [4]:
data

Ticker            VNQ
Price            Open       High        Low      Close   Volume
Date
2004-09-29  20.449881  20.507314  20.445779  20.449881   205800
2004-09-30  20.511411  20.646787  20.507309  20.613968    27900
2004-10-01  20.654995  21.024201  20.613973  20.995485   129800
2004-10-04  21.081634  21.147271  21.081634  21.085737     8100
2004-10-05  21.085743  21.126766  21.065231  21.081640    11900
...               ...        ...        ...        ...      ...
2024-12-24  87.649629  88.599867  87.610035  88.500885  2182600
2024-12-26  88.263319  88.827523  87.827798  88.738441  2577400
2024-12-27  88.213828  88.857213  87.600130  87.847588  3816700
2024-12-30  87.520946  87.659522  86.550915  87.412064  4402400
2024-12-31  88.065350  88.382096  87.382364  88.174232  5045100

[5099 rows x 5 columns]